version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8100:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
  php:
    image: php:7.2-fpm
    volumes:
      - ./:/var/www
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: chess
      MYSQL_ROOT_PASSWORD: rootchess
      MYSQL_USER: chessuser
      MYSQL_PASSWORD: chesspass
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: