version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8100:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build:
      context: .
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootchess
      - MYSQL_DATABASE=chess
      - MYSQL_USER=chessuser
      - MYSQL_PASSWORD=chesspass
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']